### ISSUE TITLE
undefined method Idno\Core\Idno::getAdmins()

### ISSUE THREAD

**Issue by traumschule** [idno/ApplyToJoin#3]
Hi! I don't know why this happens on a fresh instance with the ApplyToJoin plugin enabled after entering data to add a new user:
> Something went wrong.
> Call to undefined method Idno\Core\Idno::getAdmins()
> Click here to try again or click here to go back to the homepage.

**Comment by benwerd** [comment]
Hi there! It's worth checking to see if you're running on the latest Known codebase - unfortunately the installation package is pretty old. (Version 1.0 is coming soon.)

**Comment by traumschule** [comment]
I installed the git master version of known and this plugin. Are they incompatible?
> Apply to Join 0.1
> Version: 0.9.9-a

**Comment by benwerd** [comment]
My apologies - you're right. I've just committed a change to this plugin which should help.

**Comment by traumschule** [comment]
No worries and thanks for the fast help! Now i see:
> Too few arguments to function Idno\Core\Admin::getAdmins(), 0 passed in .../IdnoPlugins/ApplyToJoin/Pages/Join.php on line 58 and exactly 2 expected

**Comment by benwerd** [comment]
The above commit should fix this - please re-open if it didn't! I've got a fix pending in the core code at https://github.com/idno/known/pull/2303

**Comment by traumschule** [comment]
Now it works! Also with email notification (#4).
